config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/welcome', to: 'home#welcome'

  get 'home/index'
  get '/home/new',  to:     'home#new'
  get '/appointments/token', to: 'appointments#generate_token' 
  get '/appointments', to: 'appointments#index'
  post '/appointments', to: 'appointments#create'
  get  '/appointments/new', to: 'appointments#new'
  delete '/appointments/:id', to: 'appointments#destroy'
  get '/appointments/:id/change_status', to: 'appointments#change_status'   
  # default_url_options host: 'localhost:3000'
  # mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!
  def index
    # render plain: current_user.inspect
    # User.new params
  end

  def welcome
    render layout: false
  end

  # def generate_token
  #   self.token = SecureRandom.urlsafe_base64
  #   generate_token if User.exists?(token: self.token)
    
  # end

end

app/views/home/_appointment.html.erb
<div class="wrapper">
  <div class="container">
<%= form_with scope: :appointment, url: '/appointments',  local: true do |form| %>
    <% if flash[:error].present? %>
      <p>
        <%= flash[:error] %>
      </p>
    <% end %>

    <p>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name  %>
    </p>
    <p>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name  %>
    </p>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email  %>
    </p>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title  %>
    </p>
    <p>
      <%= form.label :start_date %><br>
      <%= form.text_field :start_date, :placeholder => 'dd/mm/yyyy', class: "datepicker" %>
    </p>
     <p>
      <%= form.label :end_date %><br>
      <%= form.text_field :end_date, :placeholder => 'dd/mm/yyyy', class: "datepicker" %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description  %>
    </p>
     <p>
      <%= form.submit %>
    </p>
  <% end %>
  </div>
</div>
  <script>
   $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' });
  </script>

app/views/home/index.html.erb
<div class="wrapper">
  <div class="container">
    <!-- start send token -->
    <div>
      <h3>Send Token</h3>
      <% if params[:token].present? %>
      <p>
      <%= "http://localhost:3000/appointments/new?token=" + params[:token]%>
      </p>
        <%#= params[:token] %>
        <%end%>
        <%= link_to 'generate token',  appointments_token_path%>
    </div>
    <!-- end send token -->
    <div> 
      <%= link_to "Self Appointment", appointments_new_path %><br>
      <%#= button_to "Create Self Appointment", appointments_new_path , :method => "get" %>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    <div class="col-lg-12">
      <div id="calendar"></div>
  </div> 
  </div>
</div>

<script type="text/javascript">
  $('#calendar').fullCalendar({
    events: '/appointments'

  });


  
</script>

app/views/home/new.html.erb
<%= render partial: "home/appointment" %>